// Code generated by protoc-gen-go.
// source: proto/signup_form.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto/signup_form.proto
	proto/signup_form_response.proto

It has these top-level messages:
	SignupForm
	SignupFormResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type SignupForm struct {
	Email    string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Fullname string `protobuf:"bytes,3,opt,name=fullname" json:"fullname,omitempty"`
}

func (m *SignupForm) Reset()                    { *m = SignupForm{} }
func (m *SignupForm) String() string            { return proto1.CompactTextString(m) }
func (*SignupForm) ProtoMessage()               {}
func (*SignupForm) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SignupForm) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignupForm) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SignupForm) GetFullname() string {
	if m != nil {
		return m.Fullname
	}
	return ""
}

func init() {
	proto1.RegisterType((*SignupForm)(nil), "proto.SignupForm")
}

func init() { proto1.RegisterFile("proto/signup_form.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 113 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0xce, 0x4c, 0xcf, 0x2b, 0x2d, 0x88, 0x4f, 0xcb, 0x2f, 0xca, 0xd5, 0x03, 0x8b,
	0x08, 0xb1, 0x82, 0x29, 0xa5, 0x28, 0x2e, 0xae, 0x60, 0xb0, 0x9c, 0x5b, 0x7e, 0x51, 0xae, 0x90,
	0x08, 0x17, 0x6b, 0x6a, 0x6e, 0x62, 0x66, 0x8e, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x84,
	0x23, 0x24, 0xc5, 0xc5, 0x51, 0x5a, 0x9c, 0x5a, 0x94, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0x04, 0x96,
	0x80, 0xf3, 0x41, 0x72, 0x69, 0xa5, 0x39, 0x39, 0x60, 0x39, 0x66, 0x88, 0x1c, 0x8c, 0x9f, 0xc4,
	0x06, 0xb6, 0xc2, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x7b, 0x7f, 0x65, 0x84, 0x00, 0x00,
	0x00,
}
